import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";

export const metadata: Metadata = {
  title: "Up Scale",
  description: "Generated by create next app",
};

const header = (
  <header className="">
   <NavBar />
  </header>
);

const footer = (
  <footer className="flex items-center justify-center p-4 bg-gray-800 text-white z-1">
    © 2025 Up Scale
  </footer>
);

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/helvetica-neue-55" rel="stylesheet"/>
                
      </head>
      <body className="flex flex-col  ">
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
